kamaradclimber/rte-ecowatt

README.md

Change-Id: I5f8c77589bd16324dfc7ef00d8809a808f99ccfb

📝 Add one-click badge for hacs

---

custom_components/rte_ecowatt/strings.json
custom_components/rte_ecowatt/translations/en.json

I still don't know why those two files apparently need to match but they
can't be symlinked.
Change-Id: Id63e8e1c065fbcbc4e64407ee983aec4f0cb929f

🐛 Duplicate strings.json file

---

custom_components/rte_ecowatt/__init__.py
custom_components/rte_ecowatt/config_flow.py
custom_components/rte_ecowatt/strings.json
custom_components/rte_ecowatt/translations/en.json
custom_components/rte_ecowatt/translations/fr.json

Downsides:
- code is mostly a duplicate of ConfigFlow class
- I could not succeed to allow deletion of sensors
Change-Id: Ifc580fb5e9b9c7e1e3a044cf1cce47a2c49e8154

⚙ Allow reconfiguration of sensors

---

custom_components/rte_ecowatt/config_flow.py

:bug: Compatibility with python 3.9

---

custom_components/rte_ecowatt/__init__.py

RTE announced 2 planned maintenances for their apis. To avoid having error in logs, we now have a list of planned maintenance and avoid querying api during those time.
We could be a bit cautious and extend the maintenance window by default but let's be optimistic.
Change-Id: If348c7f04e0b7270a26bc81a2e250bcc5d578c91

✨ Avoid querying RTE api during planned maintenance

---

custom_components/rte_ecowatt/__init__.py
custom_components/rte_ecowatt/config_flow.py
custom_components/rte_ecowatt/const.py
custom_components/rte_ecowatt/sensor.py
custom_components/rte_ecowatt/strings.json
custom_components/rte_ecowatt/translations/en.json
custom_components/rte_ecowatt/translations/fr.json

This comes from https://coupures-temporaires.enedis.fr/ website
Remaining to do:
- real test data with proper date parsing
Known bug: for some reason we need to restart HA to be able to add new sensors (it works once and then does not anymore until we restart HA).
Change-Id: I7e64e617f42c5369329105755ca50f4324e2c1d8

✨ Expose Enedis load shedding

---

README.en.md
README.md
custom_components/rte_ecowatt/__init__.py
custom_components/rte_ecowatt/config_flow.py
custom_components/rte_ecowatt/sensor.py

Change-Id: I365f3d8d4bd4e1f7554e47828de3079761fd97b2

:sparkles: Expose diagnostic information for Enedis sub-integration

---

custom_components/rte_ecowatt/__init__.py

This is more idiomatic than "next downgraded period" sensor we current have.
Change-Id: Ic6a60adc8a6a2d88f3b44eaade87408a63b42ba9

✨ Expose downgraded events as calendar events

---

custom_components/rte_ecowatt/__init__.py
custom_components/rte_ecowatt/calendar.py
custom_components/rte_ecowatt/sensor.py

Change-Id: I48ea8e4a2792f246f827271a6c4e79a49691705e

✨ Expose Enedis load shedding events as calendar

---

custom_components/rte_ecowatt/__init__.py
custom_components/rte_ecowatt/sensor.py

This will help to see data sent to Enedis.
Change-Id: I1c990d14d2fa10069ebf70612b2e21c3d5398bf2

✨ Expose detected address as diagnostic sensor

---

custom_components/rte_ecowatt/__init__.py

Fix #44
Change-Id: I7b0d9774a5501c92134150d5b236d97deb1406c8

✨ Group RTE entities under a RTE device

---

custom_components/rte_ecowatt/__init__.py

See #49 for detail and API response sample
Fix #49
Change-Id: I42a180c562d8130a6a3c5b621554162b2f23a914

🐛 Fix date parsing from Enedis API

---

custom_components/rte_ecowatt/__init__.py
custom_components/rte_ecowatt/config_flow.py

Fix #56
Change-Id: I5a4118f7d24e4ab60ec428942f3ea97200cc8651

🚨 Fix warning about async_setup_platform

---

custom_components/rte_ecowatt/manifest.json

This is now required by hassfest check
Change-Id: I1dcb39d5f39ee65ccc54bacaf10cc5532b06b534

🚨 Lint manifest file

---

custom_components/rte_ecowatt/__init__.py

🐛 Deal case when D+3 level is not published yet

---

custom_components/rte_ecowatt/__init__.py

This patch will avoid to get an error from the API upon HA restart by caching the api data and reusing this after HA restart.

✨ Improve behavior upon restart

---

custom_components/rte_ecowatt/__init__.py

🔎 Improve context when cached/fetched data is invalid

---

custom_components/rte_ecowatt/__init__.py

This should help people having issues and trying to solve it by uninstall/reinstall (like #82)

⚙ Remove cache upon integration uninstallation

---

custom_components/rte_ecowatt/__init__.py

This should help further issues like #82

🔎 Add broken cache file when necessary

---

custom_components/rte_ecowatt/__init__.py

This will make it easier to know all existing values

Expose all possible options

---

custom_components/rte_ecowatt/__init__.py

This version of the api has been deprecated a long time ago and stopped on June 30th

💥 Remove compatibility with api v4
